[general]
# Directories to search for templates, relative to the crate root.
dirs = ["../actix-engine/engine/static/vcg/templates","../actix-engine/engine/static/base/templates"]
# Unless you add a `-` in a block, whitespace characters won't be trimmed.

