[package]
name = "homepage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app_plugin = { path = "../app_plugin"}
actix-web = "4.*"
actix-files = "*"
async-trait = "*"
askama = "*"